# fly.toml app configuration file generated for crm-backend-rolling-harborlight-9119 on 2026-06-16T17:02:44+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crm-backend-rolling-harborlight-9119'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '4000'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
